version: "3.2"
services:
  n34_mysql:
    image: mysql
    container_name: n34_mysql
    networks:
      - n34
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/mysql-conf:/etc/mysql/conf
      - ./mysql/mysql-logs:/logs
      - ./mysql/mysql-data:/var/lib/mysql
    env_file:
      - ./mysql/mysql.env

  n34_backend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - n34_mysql
    container_name: n34_backend
    networks:
      - n34
    ports:
      - "8080:8080"

  n34_nginx:
    image: nginx
    container_name: n34_nginx
    networks:
      - n34
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx-conf:/etc/nginx
      - ./nginx/nginx-logs:/var/log/nginx
      - ./frontend:/usr/share/nginx/html/

networks:
  n34:
    external: true