spring:
  datasource:
    url: jdbc:mysql://n34_mysql:3306/n34
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true

n34:
  resource:
    resource-dir-path: /n34-space-resources
    post-dir-name: posts