spring:
  datasource:
    url: jdbc:mysql://localhost:3306/n34
    username: root
    password: 123456

server:
  error:
    include-message: ALWAYS

mybatis-plus:
  global-config:
    db-config:
      id-type: auto